export const FRONTEND_DATE_FORMAT = 'DD.MM.YYYY';
export const FRONTEND_TIME_FORMAT = 'HH:mm';
export const FRONTEND_DATETIME_FORMAT = `${FRONTEND_DATE_FORMAT} ${FRONTEND_TIME_FORMAT}`;

export const BACKEND_DATETIME_FORMAT = 'YYYY-MM-DDTHH:mm:ss.SSSZ';
